# permissions for end users to edit snssaiinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snssaiinfo-editor-role
rules:
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - snssaiinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networkfunction.nephio.io
  resources:
  - snssaiinfoes/status
  verbs:
  - get
