apiVersion: nf.nephio.org/v1alpha1
kind: SMFDeployment
metadata:
  labels:
    app.kubernetes.io/name: smfdeployment
    app.kubernetes.io/instance: smfdeployment-sample
    app.kubernetes.io/part-of: nephio-5gc-controller
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: nephio-5gc-controller
  name: smfdeployment-sample
spec:
  # TODO(user): Add fields here
